name: Playwright end-to-end tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  run_playwright_tests_job:
    runs-on: ubuntu-latest
    name: Run Playwright tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Setup CI for browser tests
        uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm install
      - name: Run dev server
        run: npm start & npx wait-on http://localhost:3000
      - name: "[Desktop/Chromium] Run Playwright tests"
        run: npx folio -p browserName=chromium -p screenshotOnFailure
        env:
          APP_URL: http://localhost:3000
      - name: "[Mobile/Safari] Run Playwright tests"
        run: npx folio -p browserName=webkit -p screenshotOnFailure -p isMobile
        env:
          APP_URL: http://localhost:3000
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: test-results
